version: '3'

services:
  python-app:
    container_name: app
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - CLICKHOUSE_HOST=clickhouse
  clickhouse:
    container_name: clickhose
    hostname: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
    environment:
      - CLICKHOUSE_PASSWORD=default
